export const Data_c1 = [
  {
    title: "Apartament 1",
    etaj: "etajul 1",
    src: "/images/C1/etaj_1/AP 4.jpg",
    liber: "true",
    camere: "3",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 4,
  },
  {
    title: "Apartament 2",
    etaj: "et_1",
    src: "/images/C1/etaj_1/AP 5.jpg",
    liber: "true",
    camere: "2",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 5,
  },
  {
    title: "Apartament 3",
    etaj: "et_1",
    src: "/images/C1/etaj_1/AP 6.jpg",
    liber: "true",
    camere: "2",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 6,
  },
  {
    title: "Apartament 4",
    etaj: "et_1",
    src: "/images/C1/etaj_1/AP 7.jpg",
    liber: "true",
    camere: "2",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 7,
  },
  {
    title: "Apartament 5",
    etaj: "et_1",
    src: "/images/C1/etaj_1/AP 8.jpg",
    liber: "true",
    camere: "3",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 8,
  },
  {
    title: "Apartament 6",
    etaj: "et_1",
    src: "/images/C1/etaj_1/AP 9.jpg",
    liber: "true",
    camere: "3",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 9,
  },
  {
    title: "Apartament 7",
    etaj: "et_2",
    src: "/images/C1/etaj_1/AP 10.jpg",
    liber: "true",
    camere: "3",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 10,
  },
  {
    title: "Apartament 8",
    etaj: "et_2",
    src: "/images/C1/etaj_1/AP 11.jpg",
    liber: "true",
    camere: "2",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 11,
  },
  {
    title: "Apartament 9",
    etaj: "et_2",
    src: "/images/C1/etaj_1/AP 12.jpg",
    liber: "true",
    camere: "2",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 12,
  },
  {
    title: "Apartament 10",
    etaj: "et_2",
    src: "/images/C1/etaj_1/AP 13.jpg",
    liber: "true",
    camere: "2",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 13,
  },
  {
    title: "Apartament 11",
    etaj: "et_2",
    src: "/images/C1/etaj_1/AP 14.jpg",
    liber: "true",
    camere: "3",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 14,
  },
  {
    title: "Apartament 12",
    etaj: "et_2",
    src: "/images/C1/etaj_1/AP 15.jpg",
    liber: "true",
    camere: "3",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 15,
  },
  {
    title: "Apartament 13",
    etaj: "et_3",
    src: "/images/C1/etaj_1/AP 16.jpg",
    liber: "true",
    camere: "3",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 16,
  },
  {
    title: "Apartament 14",
    etaj: "et_3",
    src: "/images/C1/etaj_1/AP 17.jpg",
    liber: "true",
    camere: "2",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 17,
  },
  {
    title: "Apartament 15",
    etaj: "et_3",
    src: "/images/C1/etaj_1/AP 18.jpg",
    liber: "true",
    camere: "2",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 18,
  },
  {
    title: "Apartament 16",
    etaj: "et_3",
    src: "/images/C1/etaj_1/AP 19.jpg",
    liber: "true",
    camere: "2",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 19,
  },
  {
    title: "Apartament 17",
    etaj: "et_3",
    src: "/images/C1/etaj_1/AP 20.jpg",
    liber: "true",
    camere: "3",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 20,
  },
  {
    title: "Apartament 18",
    etaj: "et_3",
    src: "/images/C1/etaj_1/AP 21.jpg",
    liber: "true",
    camere: "3",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 21,
  },
  {
    title: "Apartament 19",
    etaj: "et_4",
    src: "/images/C1/etaj_1/AP 22.jpg",
    liber: "true",
    camere: "3",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 22,
  },
  {
    title: "Apartament 20",
    etaj: "et_4",
    src: "/images/C1/etaj_1/AP 23.jpg",
    liber: "true",
    camere: "2",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 23,
  },
  {
    title: "Apartament 21",
    etaj: "et_4",
    src: "/images/C1/etaj_1/AP 24.jpg",
    liber: "true",
    camere: "2",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 24,
  },
  {
    title: "Apartament 22",
    etaj: "et_4",
    src: "/images/C1/etaj_1/AP 25.jpg",
    liber: "true",
    camere: "2",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 25,
  },
  {
    title: "Apartament 23",
    etaj: "et_4",
    src: "/images/C1/etaj_1/AP 26.jpg",
    liber: "true",
    camere: "3",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 26,
  },
  {
    title: "Apartament 24",
    etaj: "et_4",
    src: "/images/C1/etaj_1/AP 27.jpg",
    liber: "true",
    camere: "3",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 27,
  },
  {
    title: "Apartament 25",
    etaj: "et_5",
    src: "/images/C1/etaj_1/AP 28.jpg",
    liber: "true",
    camere: "3",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 28,
  },
  {
    title: "Apartament 26",
    etaj: "et_5",
    src: "/images/C1/etaj_1/AP 29.jpg",
    liber: "true",
    camere: "2",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 29,
  },
  {
    title: "Apartament 27",
    etaj: "et_5",
    src: "/images/C1/etaj_1/AP 30.jpg",
    liber: "true",
    camere: "2",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 30,
  },
  {
    title: "Apartament 28",
    etaj: "et_5",
    src: "/images/C1/etaj_1/AP 31.jpg",
    liber: "true",
    camere: "2",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 31,
  },
  {
    title: "Apartament 29",
    etaj: "et_5",
    src: "/images/C1/etaj_1/AP 32.jpg",
    liber: "true",
    camere: "3",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 32,
  },
  {
    title: "Apartament 30",
    etaj: "et_5",
    src: "/images/C1/etaj_1/AP 33.jpg",
    liber: "true",
    camere: "3",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 33,
  },
  {
    title: "Apartament 31",
    etaj: "et_6",
    src: "/images/C1/etaj_1/AP 34.jpg",
    liber: "true",
    camere: "3",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 34,
  },
  {
    title: "Apartament 32",
    etaj: "et_6",
    src: "/images/C1/etaj_1/AP 35.jpg",
    liber: "true",
    camere: "2",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 35,
  },
  {
    title: "Apartament 33",
    etaj: "et_6",
    src: "/images/C1/etaj_1/AP 36.jpg",
    liber: "true",
    camere: "2",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 36,
  },
  {
    title: "Apartament 34",
    etaj: "et_6",
    src: "/images/C1/etaj_1/AP 37.jpg",
    liber: "true",
    camere: "2",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 37,
  },
  {
    title: "Apartament 35",
    etaj: "et_6",
    src: "/images/C1/etaj_1/AP 38.jpg",
    liber: "true",
    camere: "3",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 38,
  },
  {
    title: "Apartament 36",
    etaj: "et_6",
    src: "/images/C1/etaj_1/AP 39.jpg",
    liber: "true",
    camere: "3",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 39,
  },
  {
    title: "Apartament 37",
    etaj: "et_7",
    src: "/images/C1/etaj_1/AP 40.jpg",
    liber: "true",
    camere: "3",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 40,
  },
  {
    title: "Apartament 38",
    etaj: "et_7",
    src: "/images/C1/etaj_1/AP 41.jpg",
    liber: "true",
    camere: "2",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 41,
  },
  {
    title: "Apartament 39",
    etaj: "et_7",
    src: "/images/C1/etaj_1/AP 42.jpg",
    liber: "true",
    camere: "2",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 42,
  },
  {
    title: "Apartament 40",
    etaj: "et_7",
    src: "/images/C1/etaj_1/AP 43.jpg",
    liber: "true",
    camere: "2",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 43,
  },
  {
    title: "Apartament 41",
    etaj: "et_7",
    src: "/images/C1/etaj_1/AP 44.jpg",
    liber: "true",
    camere: "3",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 44,
  },
  {
    title: "Apartament 42",
    etaj: "et_7",
    src: "/images/C1/etaj_1/AP 45.jpg",
    liber: "true",
    camere: "3",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 45,
  },
  {
    title: "Apartament 43",
    etaj: "et_8",
    src: "/images/C1/etaj_1/AP 46.jpg",
    liber: "true",
    camere: "3",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 46,
  },
  {
    title: "Apartament 44",
    etaj: "et_8",
    src: "/images/C1/etaj_1/AP 47.jpg",
    liber: "true",
    camere: "3",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 47,
  },
  {
    title: "Apartament 45",
    etaj: "et_8",

    src: "/images/C1/etaj_1/AP 48.jpg",
    liber: "true",
    camere: "3",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 48,
  },
  {
    title: "Apartament 46",
    etaj: "et_8",
    src: "/images/C1/etaj_1/AP 49.jpg",
    liber: "true",
    camere: "3",
    scara: "C 1",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 49,
  },


  {
    title: "Apartament 1",
    etaj: "parter",
    src: "/images/C2/etaj_1/AP 1.jpg",
    camere: "3",
    scara: "C 2",
    liber: "true",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 50,
  },
  {
    title: "Apartament 2",
    etaj: "parter",
    src: "/images/C2/etaj_1/AP 2.jpg",
    liber: "true",
    camere: "2",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 51,
  },
  {
    title: "Apartament 3",
    etaj: "parter",
    src: "/images/C2/etaj_1/AP 3.jpg",
    liber: "true",
    camere: "2",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 52,
  },
  {
    title: "Apartament 1",
    etaj: "etajul 1",
    src: "/images/C2/etaj_1/AP 4.jpg",
    liber: "true",
    camere: "3",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 53,
  },
  {
    title: "Apartament 2",
    etaj: "et_1",
    src: "/images/C2/etaj_1/AP 5.jpg",
    liber: "true",
    camere: "2",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 54,
  },
  {
    title: "Apartament 3",
    etaj: "et_1",
    src: "/images/C2/etaj_1/AP 6.jpg",
    liber: "true",
    camere: "2",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 55,
  },
  {
    title: "Apartament 4",
    etaj: "et_1",
    src: "/images/C2/etaj_1/AP 7.jpg",
    liber: "true",
    camere: "2",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 56,
  },
  {
    title: "Apartament 5",
    etaj: "et_1",
    src: "/images/C2/etaj_1/AP 8.jpg",
    liber: "true",
    camere: "3",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 57,
  },
  {
    title: "Apartament 6",
    etaj: "et_1",
    src: "/images/C2/etaj_1/AP 9.jpg",
    liber: "true",
    camere: "3",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 58,
  },
  {
    title: "Apartament 7",
    etaj: "et_2",
    src: "/images/C2/etaj_1/AP 10.jpg",
    liber: "true",
    camere: "3",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 59,
  },
  {
    title: "Apartament 8",
    etaj: "et_2",
    src: "/images/C2/etaj_1/AP 11.jpg",
    liber: "true",
    camere: "2",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 60,
  },
  {
    title: "Apartament 9",
    src: "/images/C2/etaj_1/AP 12.jpg",
    etaj: "et_2",
    liber: "true",
    camere: "2",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 61,
  },
  {
    title: "Apartament 10",
    etaj: "et_2",
    src: "/images/C2/etaj_1/AP 13.jpg",
    liber: "true",
    camere: "2",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 62,
  },
  {
    title: "Apartament 11",
    etaj: "et_2",
    src: "/images/C2/etaj_1/AP 14.jpg",
    liber: "true",
    camere: "3",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 63,
  },
  {
    title: "Apartament 12",
    etaj: "et_2",
    src: "/images/C2/etaj_1/AP 15.jpg",
    liber: "true",
    camere: "3",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 64,
  },
  {
    title: "Apartament 13",
    etaj: "et_3",
    src: "/images/C2/etaj_1/AP 16.jpg",
    liber: "true",
    camere: "3",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 65,
  },
  {
    title: "Apartament 14",
    etaj: "et_3",
    src: "/images/C2/etaj_1/AP 17.jpg",
    liber: "true",
    camere: "2",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 66,
  },
  {
    title: "Apartament 15",
    etaj: "et_3",
    src: "/images/C2/etaj_1/AP 18.jpg",
    liber: "true",
    camere: "2",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 67,
  },
  {
    title: "Apartament 16",
    etaj: "et_3",
    src: "/images/C2/etaj_1/AP 19.jpg",
    liber: "true",
    camere: "2",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 68,
  },
  {
    title: "Apartament 17",
    etaj: "et_3",
    src: "/images/C2/etaj_1/AP 20.jpg",
    liber: "true",
    camere: "3",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 69,
  },
  {
    title: "Apartament 18",
    etaj: "et_3",
    src: "/images/C2/etaj_1/AP 21.jpg",
    liber: "true",
    camere: "3",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 70,
  },
  {
    title: "Apartament 19",
    etaj: "et_4",
    src: "/images/C2/etaj_1/AP 22.jpg",
    liber: "true",
    camere: "3",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 71,
  },
  {
    title: "Apartament 20",
    etaj: "et_4",
    src: "/images/C2/etaj_1/AP 23.jpg",
    liber: "true",
    camere: "2",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 72,
  },
  {
    title: "Apartament 21",
    etaj: "et_4",
    src: "/images/C2/etaj_1/AP 24.jpg",
    liber: "true",
    camere: "2",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 73,
  },
  {
    title: "Apartament 22",
    etaj: "et_4",
    src: "/images/C2/etaj_1/AP 25.jpg",
    liber: "true",
    camere: "2",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 74,
  },
  {
    title: "Apartament 23",
    etaj: "et_4",
    src: "/images/C2/etaj_1/AP 26.jpg",
    liber: "true",
    camere: "3",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 75,
  },
  {
    title: "Apartament 24",
    etaj: "et_4",
    src: "/images/C2/etaj_1/AP 27.jpg",
    liber: "true",
    camere: "3",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 76,
  },
  {
    title: "Apartament 25",
    etaj: "et_5",
    src: "/images/C2/etaj_1/AP 28.jpg",
    liber: "true",
    camere: "3",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 77,
  },
  {
    title: "Apartament 26",
    etaj: "et_5",
    src: "/images/C2/etaj_1/AP 29.jpg",
    liber: "true",
    camere: "2",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 78,
  },
  {
    title: "Apartament 27",
    etaj: "et_5",
    src: "/images/C2/etaj_1/AP 30.jpg",
    liber: "true",
    camere: "2",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 79,
  },
  {
    title: "Apartament 28",
    etaj: "et_5",
    src: "/images/C2/etaj_1/AP 31.jpg",
    liber: "true",
    camere: "2",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 80,
  },
  {
    title: "Apartament 29",
    etaj: "et_5",
    src: "/images/C2/etaj_1/AP 32.jpg",
    liber: "true",
    camere: "3",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 81,
  },
  {
    title: "Apartament 30",
    etaj: "et_5",
    src: "/images/C2/etaj_1/AP 33.jpg",
    liber: "true",
    camere: "3",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 82,
  },
  {
    title: "Apartament 31",
    etaj: "et_6",
    src: "/images/C2/etaj_1/AP 34.jpg",
    liber: "true",
    camere: "3",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 83,
  },
  {
    title: "Apartament 32",
    etaj: "et_6",
    src: "/images/C2/etaj_1/AP 35.jpg",
    liber: "true",
    camere: "2",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 84,
  },
  {
    title: "Apartament 33",
    etaj: "et_6",
    src: "/images/C2/etaj_1/AP 36.jpg",
    liber: "true",
    camere: "2",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 85,
  },
  {
    title: "Apartament 34",
    etaj: "et_6",
    src: "/images/C2/etaj_1/AP 37.jpg",
    liber: "true",
    camere: "2",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 86,
  },
  {
    title: "Apartament 35",
    etaj: "et_6",
    src: "/images/C2/etaj_1/AP 38.jpg",
    liber: "true",
    camere: "3",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 87,
  },
  {
    title: "Apartament 36",
    etaj: "et_6",
    src: "/images/C2/etaj_1/AP 39.jpg",
    liber: "true",
    camere: "3",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 88,
  },
  {
    title: "Apartament 37",
    etaj: "et_7",
    src: "/images/C2/etaj_1/AP 40.jpg",
    liber: "true",
    camere: "3",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 89,
  },
  {
    title: "Apartament 38",
    etaj: "et_7",
    src: "/images/C2/etaj_1/AP 41.jpg",
    liber: "true",
    camere: "2",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 90,
  },
  {
    title: "Apartament 39",
    etaj: "et_7",
    src: "/images/C2/etaj_1/AP 42.jpg",
    liber: "true",
    camere: "2",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 91,
  },
  {
    title: "Apartament 40",
    etaj: "et_7",
    src: "/images/C2/etaj_1/AP 43.jpg",
    liber: "true",
    camere: "2",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 92,
  },
  {
    title: "Apartament 41",
    etaj: "et_7",
    src: "/images/C2/etaj_1/AP 44.jpg",
    liber: "true",
    camere: "3",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 93,
  },
  {
    title: "Apartament 42",
    etaj: "et_7",
    src: "/images/C2/etaj_1/AP 45.jpg",
    liber: "true",
    camere: "3",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 94,
  },
  {
    title: "Apartament 43",
    etaj: "et_8",
    src: "/images/C2/etaj_1/AP 46.jpg",
    liber: "true",
    camere: "3",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 95,
  },
  {
    title: "Apartament 44",
    etaj: "et_8",
    src: "/images/C2/etaj_1/AP 47.jpg",
    liber: "true",
    camere: "3",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 96,
  },
  {
    title: "Apartament 45",
    etaj: "et_8",
    src: "/images/C2/etaj_1/AP 48.jpg",
    liber: "true",
    camere: "3",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 97,
  },
  {
    title: "Apartament 46",
    etaj: "et_8",
    src: "/images/C2/etaj_1/AP 49.jpg",
    liber: "true",
    camere: "3",
    scara: "C 2",
    descriere:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quaerat iste distinctio eligendi adipisci atque, doloribus dolor hic harum voluptatem!",
    id: 98,
  },
];
